import localFont from "next/font/local";
import "./globals.css";

// Import Swiper styles
import "swiper/css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "swiper/css/pagination";
import { ReactQueryClientProvider } from "./components/ReactQueryClientProvider";

const helveticaNowDisplay = localFont({
  src: [
    {
      path: "./assets/fonts/helvetica-now-display/HelveticaNowDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/helvetica-now-display/HelveticaNowDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/helvetica-now-display/HelveticaNowDisplay-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now-display",
});

const plainFont = localFont({
  src: [
    {
      path: "./assets/fonts/plain/Plain-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/plain/Plain-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./assets/fonts/plain/Plain-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/plain/Plain-Extrabold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-plain",
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Punter IQ",
  description: "Generated by create next app",
};
// Create a client
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${helveticaNowDisplay.variable} ${plainFont.variable}`}
    >
      <body className={`bg-Subtle_dark`}>
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
      </body>
    </html>
  );
}
